name: coverage instrument based

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy, llvm-tools-preview
    
    - name: Install lcov
      run: sudo apt-get install lcov
      
    - name: install grcov
      run: cargo install grcov
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Run grcov
      env:
         PROJECT_NAME: "havocompare"
         RUSTFLAGS: "-Cinstrument-coverage -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
         CARGO_INCREMENTAL: 0
      run: |
         cargo +nightly build --verbose
         cargo +nightly test --verbose
         grcov . -s . --binary-path ./target/debug/ -t lcov --llvm --branch --ignore-not-existing --ignore="/*" --ignore="target/*" --ignore="tests/*"  -o lcov.info
         
    - name: Push grcov results to Coveralls via GitHub Action
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: "lcov.info"
        
